defaults:
  - model_checkpoint.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "step_{step:08d}"
  save_last: True
  auto_insert_metric_name: False
  every_n_train_steps: 100 # save checkpoint every 100 steps

model_summary:
  max_depth: -1
